const list = {
  koreanAsparagus: [
    "Korean asparagus",
    [
      [250, "grams", "soybean curd", 0],
      [70, "ml", "soy sauce", 0],
      [15, "ml", "vinegar", 0],
      [15, "ml", "vegetable oil", 0],
      [0.5, "teaspn", "koriander", 0],
      [0.5, "teaspn", "chili pepper", 0],
      [1, "teaspn", "dry paprika", 0],
      [1, "teaspn", "dry garlic", 0],
      [3, "cloves", "garlic", 0],
    ],
    "Boil the soybean curd for about 10 minutes. Remove all the water from the boiled curd and put in a dish. Mix all the other ingridients and poar them onto the curd. Mix well.",
    "images/sbcurd.jpg",
  ],
  tomatoSauce: [
    "Tomato Sauce",
    [
      [3, "tblspn", "olive oil", 0],
      [50, "grams", "diced onion", 0],
      [2, "cloves", "minced garlic", 0],
      [5, "tblspn", "tomato paste", 0],
      [795, "grams", "crushed tomatoes", 0],
      [1, "teaspn", "dried oregano", 0],
      [1, "teaspn", "dried basi", 0],
    ],
    "In a pot over medium heat, add the olive oil, onion, garlic, and tomato paste. Cook for 5-7 minutes or until the tomato paste has caramelized. Add the canned tomatoes, dried oregano, and dried basil. Reduce heat to a simmer and cook for 15-20 minutes or until the desired thickness. Add salt and pepper to taste.",
    "images/tomatosauce.jpg",
  ],
  bread: [
    "Bread",
    [
      [480, "m.liters", " lukewarm water", 0],
      [1, "env", "active dry yeast", 0],
      [500, "grams", "all-purpose flour", 0],
      [1.5, "teaspn", "kosher salt", 0],
      [1, "teaspn", "olive oil", 0],
    ],
    "Stir the yeast into the water and allow the yeast to bloom until foamy. In a large bowl, mix together the flour and salt by hand. Once incorporated, create a small well in the middle and pour in the water and yeast mixture. Mix by hand, wetting your working hand before mixing so the dough doesn’t stick to your fingers. The water and flour should come together and a form rough dough that pulls away from the sides of the bowl. If the dough is too sticky, add more flour in small increments, about 1 tablespoon at a time. If the dough is too dry, add more water, 1 tablespoon at a time. Once the dough comes together, cover and let rise until doubled in size (about 1 ½-2 hours). Uncover the dough and give it a few pokes with your finger. If the dough has risen properly, it should indent under the pressure of your finger and slowly deflate. Using your hand or a rubber spatula, start from the rim of the bowl to work the dough loose from the sides and fold it up and towards the center of the bowl. Turn the bowl 90 degrees, and repeat until all the dough has been pulled from the sides and folded towards the center. Once finished, cover and let the dough rise again for another 1 ½-2 hours. Once the dough has doubled in size again, gently transfer it from the bowl to a lightly floured surface. Sprinkle a bit of flour on top of the dough. Using your hands, begin to shape it into a loaf. Fold the dough under itself several times to form a ball, then pinch together the seams of dough underneath. Place the dough seam-side down in a clean bowl that has been lightly coated with olive oil and dusted with flour. Cover and let rise for 1 hour. Meanwhile, place a 6-quart Dutch oven (or heavy cooking pot with oven-safe lid) inside the oven. Preheat the oven to 230˚C with the pot inside for 45 minutes-1 hour. Carefully remove the pot from the oven and place it on a trivet or heat-safe surface. (Be careful! It’ll be VERY HOT.) Turn the proofed dough over onto a lightly floured surface and carefully place it inside the pot. Cover with the lid and return the pot to the oven. Bake for 45 minutes, removing the lid for the last 15 minutes. Remove bread from pot, cover, and let cool for 10 minutes before slicing.",
    "images/bread.jpeg",
  ],
  roastedChicken: [
    "Roasted Chicken",
    [
      [1, "", "sweet potato, diced", 0],
      [1, "", "lemon, sliced, seeds removed", 0],
      [360, "grams", "green beans", 0],
      [1, "tblspn", "olive oil", 0],
      [1, "tblspn", "fresh rosemary", 0],
      [1, "tblspn", "fresh thyme,", 0],
      [1, "clove", "garlic, minced", 0],
      [0.5, "teaspn", "salt, plus more to season", 0],
      [0.25, "teaspn", "ground black pepper", 0],
      [1, "", "skinless chicken breast", 0],
      [0.25, "teaspn", "paprika", 0],
    ],
    "Preheat oven to 90˚C. Add the sweet potatoes, lemon slices, green beans, olive oil, rosemary, thyme, garlic, salt, and pepper to a large bowl (or parchment paper-lined sheet tray) and toss until fully coated. Season the chicken breast with salt, pepper, and paprika. Transfer to a parchment paper-lined sheet tray and place the chicken breast on top of the vegetables (if you tossed your vegetables in a bowl). Bake until vegetables are tender and chicken is cooked through, about 20 minutes.",
    "images/chicken.jpeg",
  ],
  eggs: [
    "Boiled eggs",
    [
      [2, "", "eggs", 0],
      [2, "tblspn", "mayonnaise", 0],
    ],
    "Was the eggs and boil them for 12 minutes. Peel, and cut in half. Cover with half a tablespoon of mayonnaise.",
    "images/eggs.jpg",
  ],
  flan: [
    "Passion Fruit Flan",
    [
      [200, "grams", "sugar", 0],
      [80, "m.liters", "passion fruit juice", 0],
      [415, "m.liters", "heavy cream", 0],
      [235, "m.liters", "whole milk", 0],
      [2, "teaspn", "vanilla extract", 0],
      [2, "grams", "egg yolks", 0],
      [3, "", "eggs", 0],
    ],
    "Pour a cup of sugar 200g and 80ml of passion fruit juice into a saucepan over a medium heat. Let the sugar melt and form a golden color. Don't over stir. Take off the heat. Spoon the caramel into each ramekin, and swirl it around so the bottom is covered. Set aside to cool. In another saucepan, heat heavy cream, whole milk, vanilla extract, and two tablespoons of passion fruit juice. Stir until well mixed and hot. In a large bowl, mix egg yolks, eggs, and gradually pour in the hot passion fruit cream mixture until fully incorporated. Pour the mixture through a sieve to make the mixture smooth. Place the ramekins into a large roasting pan. Pour hot water into the pan to come roughly halfway up the sides of the ramekins. Pour the mixture into the ramekins and bake at 180˚C for 45 minutes. Let the flan cool outside the oven, and then refrigerate it for at least two hours. When you're ready to serve the flan, run a knife around the edges to loosen, place a dish over the top of the ramekin and quickly invert it.",
    "images/flan.jpeg",
  ],
};
export default list;
